### ISSUE TITLE
Next iteration of binary log format

### ISSUE THREAD

**Issue by fredemmott** [fredemmott/XRFrameTools#24]
# Header

- [x] matching timestamp from `QueryPerformanceCounter()` and a human-readable timestamp, both in UTC and local time - for #14
- [x] include `uncompressed` as sigil; may support additional values (e.g. `zstd`) without bumping the binary format version - for #25 
- [x] add `Produced by: XRFrameTools v0.0.3`; this is purely for reference/debugging. Parsers do not need to understand it

# FramePerformanceCounters

- [ ] ~~time since last frame for #20~~ taking a different approach
